### ISSUE TITLE
(file-size-impact) TypeError: directoryUrl must be a string or an url, received undefined

### ISSUE THREAD

**Issue by dmail** [openmrs/openmrs-esm-patient-chart#725]
Hello there, I made file-size-impact and I was checking who is using it on open source projects out of curiousity.

I see you have a TypeError because of the latest update. `projectDirectoryUrl` was renamed `directoryUrl` (my bad, it should have been a major update in the package version).

https://github.com/openmrs/openmrs-esm-patient-chart/blob/57010d84b03ce93765eb99dacae7a7fe8be84dd7/tools/size-generator.mjs#L40

should be updated to `directoryUrl`

**Comment by ibacher** [comment]
Thank you very much for the pointer! We'll get that fixed.

**Comment by denniskigen** [comment]
Hey @dmail, still [failing](https://github.com/openmrs/openmrs-esm-patient-chart/runs/7047486749?check_suite_focus=true), despite merging in the changes. Any other ideas?

**Comment by dmail** [comment]
Indeed, if you do `node tools/size-generator.mjs` you'll get the error. The error message is misleading, the parameter name is actually rootDirectoryUrl 😬
